# Site settings
title: "Open Science Paper"
description: "A modern web framework for publishing true Open Science papers on GitHub."
keywords: "HTML, CSS, JS"
url: ""
baseurl: "/test_gh-pages"


# authors of the publication
authors:
  - name: "JF Durand"
    mail: "jean-frederic.durand@etudiant.univ-lille1.fr"
    location: "Cité Scientifique, 59655 Villeneuve d'Ascq"
  - name: "Vasilina Frolkova"
    mail: "vasilina.frolkova@etudiant.univ-lille1.fr"
    location: "Cité Scientifique, 59655 Villeneuve d'Ascq"
  - name: "Third Person"
    mail: "third@person.com"
    location: "Somewhere"

# using git issues as comment
username: "Whispyy"
reponame: "test_gh-pages"


font-awesome-include: true # make this false if you don't need font-awesome

# Build settings
markdown: kramdown

exclude: ["README.md"]

gems:
  - jekyll-seo-tag